"""create_initial_schema

Revision ID: e240fc51380d
Revises: 
Create Date: 2026-08-14 18:33:48.012280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e240fc51380d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CONDUCTOR', 'CANDIDATE', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_voters', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'OPEN', 'CLOSED', 'RESULT_PUBLISHED', name='event_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_conductor_id'), 'events', ['conductor_id'], unique=False)
    op.create_table('credibility_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credibility_questions_event_id'), 'credibility_questions', ['event_id'], unique=False)
    op.create_table('event_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_options_event_id'), 'event_options', ['event_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'candidate_id', name='uq_event_participant')
    )
    op.create_index(op.f('ix_event_participants_candidate_id'), 'event_participants', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_event_participants_event_id'), 'event_participants', ['event_id'], unique=False)
    op.create_table('credibility_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('choice_text', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['credibility_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credibility_choices_question_id'), 'credibility_choices', ['question_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('raw_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('weighted_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('winning_option_id', sa.UUID(), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_option_id'], ['event_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_event_id'), 'results', ['event_id'], unique=True)
    op.create_index(op.f('ix_results_winning_option_id'), 'results', ['winning_option_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=False),
    sa.Column('credibility_at_vote', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['event_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'candidate_id', name='uq_event_candidate_vote')
    )
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_votes_event_id'), 'votes', ['event_id'], unique=False)
    op.create_index(op.f('ix_votes_selected_option_id'), 'votes', ['selected_option_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_choice_id', sa.UUID(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['credibility_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['credibility_choices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'question_id', name='uq_participant_question_response')
    )
    op.create_index(op.f('ix_assessment_responses_participant_id'), 'assessment_responses', ['participant_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_question_id'), 'assessment_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_selected_choice_id'), 'assessment_responses', ['selected_choice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_responses_selected_choice_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_question_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_participant_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_votes_selected_option_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_event_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_results_winning_option_id'), table_name='results')
    op.drop_index(op.f('ix_results_event_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_credibility_choices_question_id'), table_name='credibility_choices')
    op.drop_table('credibility_choices')
    op.drop_index(op.f('ix_event_participants_event_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_candidate_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_event_options_event_id'), table_name='event_options')
    op.drop_table('event_options')
    op.drop_index(op.f('ix_credibility_questions_event_id'), table_name='credibility_questions')
    op.drop_table('credibility_questions')
    op.drop_index(op.f('ix_events_conductor_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
